version: '3.8'

services:
  bind9:
    image: bind9-local
    build:
      context: .
    container_name: bind9-dns
    environment:
      - ROOT_PASSWORD=SecretPassword
    #volumes:
    #  - "./conf/dns/named.conf:/etc/bind/named.conf:ro"
    #  - "./conf/dns/zones:/etc/bind/master"
    #  - "./conf/GeoIP.acl:/etc/bind/geo/GeoIP.acl:ro"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "10000:10000/tcp"
    networks:
      custom-net:
        ipv4_address: 172.20.0.2

  ua-host:
    image: nginx
    volumes:
      - "./conf/nginx/ua.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8180:80"
    networks:
      custom-net:
        ipv4_address: 172.20.0.3

  others-host:
    image: nginx
    volumes:
      - "./conf/nginx/others.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8181:80"
    networks:
      custom-net:
        ipv4_address: 172.20.0.4

networks:
  custom-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16